# Generated by Django 5.2.9 on 2025-12-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='exclusions_old',
            field=models.TextField(blank=True, help_text='DEPRECATED: Use exclusions ManyToMany field instead', null=True),
        ),
        migrations.RemoveField(
            model_name='participant',
            name='exclusions',
        ),
        migrations.AddField(
            model_name='participant',
            name='exclusions',
            field=models.ManyToManyField(blank=True, help_text='Participants this person cannot be assigned to give gifts to', related_name='excluded_by', to='events.participant'),
        ),
    ]
