# Generated by Django 5.2.9 on 2025-12-08 02:02

from django.db import migrations


def migrate_exclusions_to_m2m(apps, schema_editor):
    """Convert TextField exclusions to ManyToMany relationships."""
    Participant = apps.get_model('events', 'Participant')

    for participant in Participant.objects.all():
        if not participant.exclusions_old:
            continue

        # Parse old exclusions field (comma or newline separated emails)
        excluded_emails = set()
        for email in participant.exclusions_old.replace('\n', ',').split(','):
            email = email.strip().lower()
            if email:
                excluded_emails.add(email)

        # Find matching participants in the same event and create M2M relationships
        for excluded_email in excluded_emails:
            try:
                excluded_participant = Participant.objects.get(
                    event=participant.event,
                    email__iexact=excluded_email
                )
                participant.exclusions.add(excluded_participant)
            except Participant.DoesNotExist:
                # Skip invalid emails that don't match any participant
                print(f"Warning: Participant {participant.email} excludes {excluded_email} but no such participant exists in event {participant.event.name}")
                continue
            except Participant.MultipleObjectsReturned:
                # This shouldn't happen due to unique constraint, but handle it anyway
                print(f"Warning: Multiple participants found with email {excluded_email} in event {participant.event.name}")
                continue


def reverse_migration(apps, schema_editor):
    """Convert ManyToMany exclusions back to TextField format."""
    Participant = apps.get_model('events', 'Participant')

    for participant in Participant.objects.all():
        excluded_emails = [p.email for p in participant.exclusions.all()]
        if excluded_emails:
            participant.exclusions_old = ', '.join(excluded_emails)
            participant.save()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_participant_exclusions_old_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_exclusions_to_m2m, reverse_migration),
    ]
