# Generated by Django 5.2.9 on 2025-12-08 02:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_migrate_exclusions_to_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name for this exclusion group (e.g., 'Smith Family', 'Marketing Team')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of this group', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusion_groups', to='events.event')),
                ('members', models.ManyToManyField(blank=True, help_text='Participants in this group will not be assigned to give gifts to each other', related_name='exclusion_groups', to='events.participant')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('event', 'name'), name='unique_group_name_per_event')],
            },
        ),
    ]
