# Generated by Django 5.2.9 on 2025-12-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_exclusiongroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='confirmation_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
