# Generated by Django 5.2.9 on 2025-12-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notification_preference',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Both Email and SMS'), ('none', 'Disable Notifications')], default='email', help_text='Preferred method for receiving notifications', max_length=10),
        ),
    ]
